In [3]:
import pandas as pd
import os
import numpy as np

In [73]:
path = 'D:\\Мои документы\\Дивиденд\\Smart-lab\\'
pathnew = 'D:\\Мои документы\\Дивиденд\\Smart-lab_edit\\'

for file in os.listdir(path):

        

        df1 = pd.DataFrame(columns=['index','Дата отчета','Валюта отчета','Выручка, млрд руб','Операционная прибыль, млрд руб','EBITDA, млрд руб',
                                    'Чистая прибыль, млрд руб','Операционный денежный поток, млрд руб','CAPEX, млрд руб','FCF, млрд руб',
                                    'Див.выплата, млрд руб','Дивиденд, руб/акцию','Див доход, ао, %','Дивиденды/прибыль, %',
                                    'Опер. расходы, млрд руб','Себестоимость, млрд руб','Амортизация, млрд руб','НИОКР, млрд руб',
                                    'Расх на персонал, млрд руб','Процентные расходы, млрд руб','Активы, млрд руб','Чистые активы, млрд руб',
                                    'Долг, млрд руб','Наличность, млрд руб','Чистый долг, млрд руб','Цена акции ао, руб','Free Float, %',
                                    'Капитализация, млрд руб','EV, млрд руб','Баланс стоимость, млрд руб','EPS, руб','FCF/акцию, руб',
                                    'BV/акцию, руб','Рентаб EBITDA, %','Чистая рентаб, %','Доходность FCF, %','ROE, %','ROA, %','P/E',
                                    'P/FCF','P/S','P/BV','EV/EBITDA','Долг/EBITDA','R&D/CAPEX, %','CAPEX/Выручка, %'])
        df = pd.read_csv(path + file, sep=";")
        
        df.dropna(axis=0, how='all',inplace=True)
        df.dropna(axis=1, how='all',inplace=True)
        
        try: 
            df.drop(columns=['LTM'], inplace=True)
        except:
            pass
        
        
        
        
        df = df.transpose()
        df.columns = df.iloc[0]
        df = df[1:]
       
        df.reset_index(level=0, inplace=True) 
        for column in df1.columns:
            try:
                df1[column] = df[column]
            except:
                df1[column] = ''
        # df1.fillna(0, inplace=True)
        df1 = df1.replace('%', '', regex=True)
        if file.count('годов') > 0:
            df1['type'] = 'FY'
        if file.count('квартал') > 0:
            df1['type'] = 'Q'
        if file.count('МСФО') > 0:
            df1['report'] = 'MSFO'
        if file.count('РСБУ') > 0:
            df1['report'] = 'RSBU'
        df1['Дата отчета'] = df1['Дата отчета'].astype('datetime64[ns]').dt.strftime('%m/%d/%Y')
        df1.to_excel(pathnew+file[:-4]+'.xlsx',index=False)
        
df1

C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('%', '', regex=True)
C:\Users\Msi-1\AppData\Local\Temp\ipykernel_30880\3804070497.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

,index,Дата отчета,Валюта отчета,"Выручка, млрд руб","Операционная прибыль, млрд руб","EBITDA, млрд руб","Чистая прибыль, млрд руб","Операционный денежный поток, млрд руб","CAPEX, млрд руб","FCF, млрд руб",...,P/E,P/FCF,P/S,P/BV,EV/EBITDA,Долг/EBITDA,"R&D/CAPEX, %","CAPEX/Выручка, %",type,report
0,2016Q4,NaN,RUB,NaN,NaN,,NaN,,,,...,NaN,,NaN,NaN,,,,NaN,Q,RSBU
1,2017Q4,12/05/2020,RUB,NaN,NaN,,NaN,,,,...,NaN,,NaN,0.94,,,,NaN,Q,RSBU
2,2018Q4,04/04/2019,RUB,NaN,NaN,,NaN,,,,...,NaN,,NaN,0.78,,,,NaN,Q,RSBU
3,2019Q4,12/05/2020,RUB,NaN,NaN,,NaN,,,,...,NaN,,NaN,2.83,,,,NaN,Q,RSBU
4,2020Q3,08/12/2021,RUB,4.72,1.67,,0.410,,,,...,101.9,,8.85,NaN,,,,0,Q,RSBU
5,2020Q4,04/20/2021,RUB,NaN,0.680,,NaN,,,,...,107.3,,9.32,4.80,,,,NaN,Q,RSBU
6,2021Q1,04/29/2022,RUB,2.56,1.22,,1.23,,,,...,61.8,,13.9,NaN,,,,0,Q,RSBU
7,2021Q2,08/29/2022,RUB,1.50,0.510,,0.268,,,,...,44.5,,9.66,NaN,,,,0,Q,RSBU
8,2021Q3,08/12/2021,RUB,1.20,0.292,,-414.0,,,,...,-0.26,,20.1,10.9,,,,0,Q,RSBU
9,2021Q4,08/04/2022,RUB,1.89,0.710,,414.0,,,,...,61.7,,12.9,8.89,,,,0,Q,RSBU
10,2022Q1,04/29/2022,RUB,2.68,1.22,,0.860,,,,...,83.2,,12.9,8.34,,,,0,Q,RSBU
11,2022Q2,08/29/2022,RUB,1.52,0.447,,0.060,,,,...,92.8,,11.7,5.99,,,,0,Q,RSBU
12,2022Q3,02/11/2022,RUB,1.22,0.100,,-0.370,,,,...,0.19,,10.9,9.06,,,,0,Q,RSBU
13,2022Q4,02/05/2023,RUB,1.90,0.663,,-0.250,,,,...,341.0,,14.0,7.03,,,,0,Q,RSBU
14,2023Q1,05/05/2023,RUB,2.60,1.19,,0.800,,,,...,417.1,,13.8,6.52,,,,0,Q,RSBU
15,2023Q2,07/31/2023,RUB,1.72,0.520,,0.290,,,,...,207.3,,13.1,6.22,,,,0,Q,RSBU
16,2023Q3,01/11/2023,RUB,1.77,0.360,,0.690,,,,...,69.4,,13.3,6.50,,,,0,Q,RSBU
17,2023Q4,05/04/2024,RUB,2.32,0.780,,-0.340,,,,...,51.1,,8.74,4.59,,,,0,Q,RSBU

In [70]:
file

'ЯТЭК-РСБУ-квартальные.csv'

In [77]:
pathnew1 = 'D:\\Мои документы\\Дивиденд\\Smart-lab_edit\\'
result = pd.DataFrame(columns=['Name'])
a = []

for file in os.listdir(pathnew1):
    a.append(file[:file.find('-')])
result['Name'] = a
result.drop_duplicates(inplace=True)   
result.to_excel('D:\\Мои документы\\Дивиденд\\Names2.xlsx', index=False)
result

                  Name
0                  En+
4            Fix Price
6          Globaltrans
8    Globaltruck (ГТМ)
12                 GTL
..                 ...
776               ЮУНК
780    Яковлев (Иркут)
784       Якутскэнерго
788             Яндекс
790               ЯТЭК

[212 rows x 1 columns]

In [10]:
names = pd.read_excel('D:\\Мои документы\\Дивиденд\\Names.xlsx')
names

                           Name     Ticker
0              Ays Stim Rus PAO       SIBG
1              Etalon Group PLC  MOEX:ETLN
2           Fix Price Group Ltd  MOEX:FIXP
3                  Gaz PAO Pref      GAZAP
4    Globaltruck Management PAO       GTRK
..                          ...        ...
245    ЭН+ Груп Интернейшнл ПАО       ENPG
246                         Южн       UNKL
247           Южный Кузбасс ОАО       UKUZ
248                  Юнипро ПАО  MOEX:UPRO
249                 Яндекс Н.В.  MOEX:YNDX

[250 rows x 2 columns]

In [33]:
pathnew1 = 'D:\\Мои документы\\Дивиденд\\Smart-lab_edit1\\'
names = pd.read_excel('D:\\Мои документы\\Дивиденд\\Names.xlsx')
for folder in os.listdir(pathnew1):
    result = pd.DataFrame()
    for file in os.listdir(pathnew1+folder+'\\'):
        df = pd.read_excel(pathnew1+folder+'\\'+file)
        name = file[:file.find('-')-1]
        ticker = names[names['Name'] == name].iloc[0,1]
        df.insert(0, "Ticker", ticker)
        result = pd.concat([result,df], ignore_index=True)
    result.to_excel('D:\\Мои документы\\Дивиденд\\' + folder + '.xlsx', index=False) 
    
result

C:\Users\Msi-1\AppData\Local\Temp\ipykernel_13704\2509167102.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result = pd.concat([result,df], ignore_index=True)

,Ticker,Дата оконч. периода,Доход,Рост выручки (год к году),Себестоимость,Валовая прибыль,Маржа валовой прибыли,Расходы на НИОКР,"Расходы на реализацию, общие и управленческие расходы",Проч. доходы/(расходы),...,Разводненная прибыль на акцию (продолж. деятельность),Средневзвешенное количество распределенных базовых акций,Средневзвешенное количество распределенных разводненных акций,EBITDA,EBIT,Доход (отчетный),Операционные доходы (отчетные),Операционные доходы (скорректир.),Расходы на реализацию и маркетинг,Общие и административные расходы
0,SIBG,03/31/2015,NaN,NaN,0.000000e+00,NaN,NaN,0,-1.050000e+02,-2.500000e+01,...,NaN,NaN,NaN,NaN,-1.050000e+02,NaN,NaN,-1.050000e+02,NaN,NaN
1,SIBG,06/30/2015,NaN,NaN,0.000000e+00,NaN,NaN,0,-1.050000e+02,-2.500000e+01,...,NaN,NaN,NaN,NaN,-1.050000e+02,NaN,NaN,-1.050000e+02,NaN,NaN
2,SIBG,09/30/2015,5.330000e+02,NaN,-3.220000e+02,2.110000e+02,39.599998,0,-1.224000e+06,-5.910000e+02,...,NaN,NaN,NaN,NaN,-1.013000e+06,5.330000e+02,NaN,-1.013000e+06,NaN,NaN
3,SIBG,03/31/2016,5.600000e+02,NaN,-4.900000e+02,7.000000e+01,12.500000,0,-8.210000e+06,-4.150000e+02,...,NaN,NaN,NaN,-8.139454e+06,-8.140000e+06,5.600000e+02,NaN,-8.140000e+06,NaN,NaN
4,SIBG,06/30/2016,5.500000e+01,NaN,-3.800000e+01,1.700000e+01,30.900000,0,-8.639000e+06,-1.716000e+06,...,-0.100000,100000000.0,100000000.0,-8.621454e+06,-8.622000e+06,5.500000e+01,NaN,-8.622000e+06,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8475,MOEX:YNDX,12/31/2021,1.103280e+11,54.099998,-5.246500e+10,5.786300e+10,52.400002,-13996000256,-3.939200e+10,-2.781000e+09,...,-12.190000,363263680.0,363263680.0,1.864000e+09,-2.603000e+09,1.103280e+11,-2.603000e+09,-2.603000e+09,NaN,NaN
8476,MOEX:YNDX,03/31/2022,1.060100e+11,44.900002,-5.101100e+10,5.499900e+10,51.900002,-19160999936,-4.080500e+10,-6.294000e+09,...,-39.560001,364570688.0,364570688.0,-4.967000e+09,-1.243400e+10,1.060100e+11,-1.243400e+10,-1.243400e+10,NaN,NaN
8477,MOEX:YNDX,06/30/2022,1.177480e+11,44.700001,-4.872100e+10,6.902700e+10,58.599998,-16826000384,-3.574200e+10,-4.599000e+09,...,-7.020000,371106752.0,376105152.0,1.645900e+10,8.746000e+09,1.177480e+11,8.746000e+09,8.746000e+09,NaN,NaN
8478,MOEX:YNDX,09/30/2022,1.331630e+11,45.799999,-5.565400e+10,7.750900e+10,58.200001,-17057999872,-4.218600e+10,3.374600e+10,...,116.230003,370925696.0,371390432.0,1.826500e+10,1.079700e+10,1.331630e+11,1.079700e+10,1.079700e+10,NaN,NaN
8479,MOEX:YNDX,12/31/2022,1.647780e+11,49.400002,-7.783300e+10,8.694500e+10,52.799999,-19232999424,-5.335900e+10,2.059000e+09,...,13.310000,370834912.0,372168448.0,1.435300e+10,6.127000e+09,1.647780e+11,6.127000e+09,6.127000e+09,NaN,NaN

In [32]:
name

'Меридиан ПИФН'